spring:
  application:
    name: Ordering-Config-Server  cloud:    config:      server:        git:          uri: https://github.com/jamietao/ordering-config
          skip-ssl-validation: true
          username: jamie.tao@perkinelmer.com
          password: Coding4ever
    
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka/
      